SELECT MEMBER_ID,MEMBER_NAME,GENDER,
DATE_FORMAT(DATE_OF_BIRTH,'%Y-%m-%d') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE MONTH(DATE_OF_BIRTH)= '03' and TLNO IS NOT NULL and GENDER='W'
ORDER BY MEMBER_ID ASC;